version: '3.7'
services:
  pabiosfile:
    container_name: pabiosfile
    build: ./pabiosfile
    ports:
      - "9000:8000" # on l'expose a l'exterieur du contenaire
    volumes:
      - ./project:/var/www/html
  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]

  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: password
      POSTGRES_USER: symfony
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432"

volumes:
  db-data: